---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: learning-go-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: learning-go-api
  policy:
    semver:
      range: '>=0.0.1 <1.0.0'

